name = "colorverse-image-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGINS = "https://dseeker.github.io"

# API key set as a secret via:
#   npx wrangler secret put POLLINATIONS_API_KEY

[[kv_namespaces]]
binding = "SITE_DATA"
id = "ff1368ad7005423b8e866d7bd8c98ef2"
